# Generated by Django 5.2.7 on 2026-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_notification_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
    ]
